---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: scheduler-issuer
  namespace: scheduler-webhook
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scheduler-webhook-cert
  namespace: scheduler-webhook
spec:
  secretName: scheduler-webhook-cert-secret
  duration: 2160h0m0s
  renewBefore: 360h0m0s
  commonName: scheduler-webhook.scheduler-webhook.svc 
  dnsNames:
    - scheduler-webhook
    - scheduler-webhook.scheduler-webhook.svc
    - scheduler-webhook.scheduler-webhook.svc.cluster.local
  issuerRef:
    name: scheduler-issuer
    kind: Issuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-webhook
  namespace: scheduler-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-webhook
  template:
    metadata:
      labels:
        app: scheduler-webhook
    spec:
      containers:
        - name: webhook
          image: iad.ocir.io/idt7ybnr03cb/hemant:094231
          # image: iad.ocir.io/idt7ybnr03cb/hemant:145822
          ports:
            - containerPort: 443
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 443
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 443
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          volumeMounts:
            - name: scheduler-webhook-cert
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: scheduler-webhook-cert
          secret:
            secretName: scheduler-webhook-cert-secret
      imagePullSecrets:
        - name: ocir-auth
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-webhook
  namespace: scheduler-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: scheduler-webhook
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: scheduler-webhook
  annotations:
    cert-manager.io/inject-ca-from: scheduler-webhook/scheduler-webhook-cert
webhooks:
  - name: webhook.scheduler-webhook.svc
    admissionReviewVersions:
      - "v1beta1"
      - "v1"
    sideEffects: "None"
    timeoutSeconds: 30
    failurePolicy: Ignore
    clientConfig:
      service:
        name: scheduler-webhook
        namespace: scheduler-webhook
        path: /mutate
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    objectSelector:
      matchExpressions:
        - key: scheduler-container-webhook-enable
          operator: In
          values:
            - "true"
            - "false"