apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-mutator
  labels:
    app: pod-mutator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-mutator
  template:
    metadata:
      labels:
        app: pod-mutator
    spec:
      containers:
        - name: pod-mutator
          image: your-docker-image # Replace with your Docker image
          ports:
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: pod-mutator
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: pod-mutator
