apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: openfaas-webhook-issuer
  namespace: dev
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openfaas-webhook-cert
  namespace: dev
spec:
  dnsNames:
    - webhook-service.dev.svc
  secretName: openfaas-webhook-cert-secret
  issuerRef:
    name: openfaas-webhook-issuer
    kind: Issuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-deployment
  template:
    metadata:
      labels:
        app: webhook-deployment
    spec:
      containers:
        - name: webhook
          image: iad.ocir.io/idt7ybnr03cb/hemant:latest0
          ports:
            - containerPort: 443
          volumeMounts:
            - name: openfaas-webhook-cert
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: openfaas-webhook-cert
          secret:
            secretName: openfaas-webhook-cert-secret
      imagePullSecrets:
        - name: ocir-auth
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: dev
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: webhook-deployment
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-configuration
webhooks:
  - name: webhook.dev.svc
    clientConfig:
      service:
        name: webhook-service
        namespace: dev
        path: /mutate
      caBundle: # This needs to be the CA bundle of the cert-manager, usually filled by cert-manager
    rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
