---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: scheduler-issuer
  namespace: jenkins
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scheduler-webhook-cert
  namespace: jenkins
spec:
  dnsNames:
    - webhook-deployment.jenkins.svc
    - webhook-deployment.jenkins.svc.cluster.local
  secretName: scheduler-webhook-cert-secret
  issuerRef:
    name: scheduler-issuer
    kind: Issuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-deployment
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-deployment
  template:
    metadata:
      labels:
        app: webhook-deployment
    spec:
      containers:
        - name: webhook
          image: iad.ocir.io/idt7ybnr03cb/hemant:094231
          ports:
            - containerPort: 443
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 443
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 443
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          volumeMounts:
            - name: scheduler-webhook-cert
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: scheduler-webhook-cert
          secret:
            secretName: scheduler-webhook-cert-secret
      imagePullSecrets:
        - name: ocir-auth
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-deployment
  namespace: jenkins
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: webhook-deployment
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: jenkins/scheduler-webhook-cert-secret
webhooks:
  - name: webhook.jenkins.svc
    admissionReviewVersions:
      - "v1beta1"
      - "v1"
    sideEffects: "None"
    timeoutSeconds: 30
    clientConfig:
      service:
        name: webhook-deployment
        namespace: jenkins
        path: /mutate
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]