apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    testing: "objectstore"
spec:
  containers:
    - name: mycontainer
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: openfaas-webhook-cert
          mountPath: /etc/webhook/certs
          readOnly: true
  volumes:
    - name: openfaas-webhook-cert
      secret:
        secretName: openfaas-webhook-cert-secret
  imagePullSecrets:
    - name: ocir-auth
