apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    logging: "objectstore"   # Label x with value y
spec:
  containers:
  - name: mycontainer
    image: busybox
    command: ["sleep", "3600"]  # Sleep for 1 hour
