service:
  port: "443"
targetLabels:
  - key: testing
    value: objectstore
tolerations:
  - key: "platform"
    operator: "Equal"
    value: "objectstore"
    effect: "NoSchedule"
nodeSelector:
  agentpool: objectstore