service:
  port: "443"
targetLabels:
  - key: testing
    value: objectstore
patch:
  tolerations:
    enable: true
    value:
      - key: "platform"
        operator: "Equal"
        value: "objectstore"
        effect: "NoSchedule"
  nodeSelector:
    enable: true
    value:
      agentpool: objectstore
  imagePullSecrets:
    enable: true
    value:
      - name: acr-auth