service:
  port: "443"
targetLabels:
  - key: scheduler-container-webhook-enable
    value: "true"
patch:
  tolerations:
    enable: true
    value:
      - key: "platform"
        operator: "Equal"
        value: "objectstore"
        effect: "NoSchedule"
  nodeSelector:
    enable: true
    value:
      agentpool: objectstore
  imagePullSecrets:
    enable: false
    value:
      - name: acr-auth